import type { Trabajador, BitacoraRentaDiaria, RegistroAsistencia, AsistenciaSemanalTrabajador } from '@svr-erp/shared/types';

export const trabajadores: Trabajador[] = [
  {
    id: "T001",
    nombre: "Juan Pérez",
    puesto: "Operador de Excavadora",
    categoriaPuesto: "Operador",
    estado: "Activo",
    entrada: "07:00 AM",
    telefono: "55 1234 5678",
    proyectos: ["Fraccionamiento Valle Sur"],
    avatar: "JP",
    sueldoFiscal: 2500,
    sueldoEfectivo: 3500,
    metodoPago: "Mixto",
    maquinaAsignadaId: "M001",
    maquinaAsignadaNombre: "Excavadora CAT 320",
    estadoRenta: "Rentado a Cliente",
    clienteRentaActual: "Inmobiliaria ARCO",
    licenciaODC3: {
      tipo: "Certificación DC-3 Excavadora Hidráulica",
      vigencia: "2026-11-30",
      folio: "DC3-CAT-8921"
    },
    fechaContratacion: "2023-03-15",
    contactoEmergencia: { nombre: "María Gómez", telefono: "55 9876 5432", parentesco: "Esposa" },
    vacacionesDias: 8,
    horasExtraSemana: 6.5,
    tarifaHoraExtra: 80,
    descuentosSemana: 0,
    conceptoDescuento: ''
  },
  {
    id: "T002",
    nombre: "Pedro Gómez",
    puesto: "Operador de Retroexcavadora",
    categoriaPuesto: "Operador",
    estado: "Activo",
    entrada: "07:00 AM",
    telefono: "55 8765 4321",
    proyectos: ["Remodelación Centro Histórico"],
    avatar: "PG",
    sueldoFiscal: 2200,
    sueldoEfectivo: 3200,
    metodoPago: "Mixto",
    maquinaAsignadaId: "M002",
    maquinaAsignadaNombre: "Retroexcavadora JD 310L",
    estadoRenta: "Rentado a Cliente",
    clienteRentaActual: "Gobierno CDMX",
    licenciaODC3: {
      tipo: "Certificación DC-3 Retroexcavadora",
      vigencia: "2026-08-15",
      folio: "DC3-JD-4412"
    },
    fechaContratacion: "2023-07-01",
    contactoEmergencia: { nombre: "Rosa Pérez", telefono: "55 1122 3344", parentesco: "Madre" },
    vacacionesDias: 6,
    horasExtraSemana: 4.5,
    tarifaHoraExtra: 75,
    descuentosSemana: 0,
    conceptoDescuento: ''
  },
  {
    id: "T003",
    nombre: "Ana Martínez",
    puesto: "Administradora de Obra",
    categoriaPuesto: "Administrativo",
    estado: "Activo",
    entrada: "08:30 AM",
    telefono: "55 2345 6789",
    proyectos: ["Oficina Central SVR"],
    avatar: "AM",
    sueldoFiscal: 5000,
    sueldoEfectivo: 2000,
    metodoPago: "Mixto",
    estadoRenta: "En Obra Propia",
    fechaContratacion: "2022-01-10",
    contactoEmergencia: { nombre: "Carlos Martínez", telefono: "55 5566 7788", parentesco: "Hermano" },
    vacacionesDias: 12,
    horasExtraSemana: 0,
    tarifaHoraExtra: 0,
    descuentosSemana: 0,
    conceptoDescuento: ''
  },
  {
    id: "T004",
    nombre: "Luis Torres",
    puesto: "Chofer de Camión Volteo",
    categoriaPuesto: "Chofer",
    estado: "Activo",
    entrada: "06:30 AM",
    telefono: "55 3456 7890",
    proyectos: ["Puente Atizapán"],
    avatar: "LT",
    sueldoFiscal: 2000,
    sueldoEfectivo: 2800,
    metodoPago: "Mixto",
    maquinaAsignadaId: "M004",
    maquinaAsignadaNombre: "Camión Volteo Kenworth 14m³",
    estadoRenta: "Rentado a Cliente",
    clienteRentaActual: "Constructora ABC / SCT",
    licenciaODC3: {
      tipo: "Licencia Federal de Chofer Tipo E",
      vigencia: "2027-02-28",
      folio: "SCT-FED-99882"
    },
    fechaContratacion: "2023-11-20",
    contactoEmergencia: { nombre: "Lucía Torres", telefono: "55 9988 7766", parentesco: "Esposa" },
    vacacionesDias: 6,
    horasExtraSemana: 0,
    tarifaHoraExtra: 65,
    descuentosSemana: 0,
    conceptoDescuento: ''
  },
  {
    id: "T005",
    nombre: "Carlos Ruiz",
    puesto: "Mecánico Diésel Especialista",
    categoriaPuesto: "Mecanico",
    estado: "Activo",
    entrada: "07:30 AM",
    telefono: "55 4567 8901",
    proyectos: ["Taller Central SVR"],
    avatar: "CR",
    sueldoFiscal: 3000,
    sueldoEfectivo: 4000,
    metodoPago: "Mixto",
    estadoRenta: "En Obra Propia",
    licenciaODC3: {
      tipo: "Certificado Diagnóstico Hidráulico CAT/JD",
      vigencia: "2027-10-15",
      folio: "MEC-CAT-3321"
    },
    fechaContratacion: "2021-05-18",
    contactoEmergencia: { nombre: "Laura Soto", telefono: "55 4433 2211", parentesco: "Esposa" },
    vacacionesDias: 14,
    horasExtraSemana: 2.0,
    tarifaHoraExtra: 90,
    descuentosSemana: 0,
    conceptoDescuento: ''
  },
  {
    id: "T006",
    nombre: "Ing. Jorge Valenzuela",
    puesto: "Ingeniero Residente de Obra",
    categoriaPuesto: "Ingeniero",
    estado: "Activo",
    entrada: "07:00 AM",
    telefono: "55 5678 9012",
    proyectos: ["Fraccionamiento Valle Sur", "Puente Atizapán"],
    avatar: "JV",
    sueldoFiscal: 6500,
    sueldoEfectivo: 4500,
    metodoPago: "Mixto",
    estadoRenta: "En Obra Propia",
    licenciaODC3: {
      tipo: "Cédula Profesional Ing. Civil",
      vigencia: "Permanente",
      folio: "CED-CIV-8849102"
    },
    fechaContratacion: "2020-02-01",
    contactoEmergencia: { nombre: "Patricia Valenzuela", telefono: "55 7788 9900", parentesco: "Hermana" },
    vacacionesDias: 15,
    horasExtraSemana: 0,
    tarifaHoraExtra: 0,
    descuentosSemana: 0,
    conceptoDescuento: ''
  }
];

export const bitacorasRentaData: BitacoraRentaDiaria[] = [
  {
    id: "B001",
    folio: "BIT-2025-042",
    trabajadorId: "T001",
    trabajadorNombre: "Juan Pérez",
    maquinaId: "M001",
    maquinaNombre: "Excavadora CAT 320",
    fecha: "2025-04-27",
    cliente: "Inmobiliaria ARCO",
    obraUbicacion: "Fraccionamiento Valle Sur (Manzana 4)",
    horaInicio: "07:00 AM",
    horaFin: "05:30 PM",
    horasEfectivas: 8.0,
    horasExtras: 2.5,
    horometroInicial: 1238.5,
    horometroFinal: 1249.0,
    actividadRealizada: "Excavación de zanja pluvial 80m lineales, afine de talud y carga de material sobrante a camiones de volteo.",
    firmaCliente: {
      firmado: true,
      nombreResidente: "Ing. Roberto Garza",
      cargoResidente: "Residente de Obra · Inmobiliaria ARCO",
      fechaFirma: "2025-04-27 05:45 PM"
    },
    estadoCobro: "Listo para Facturar",
    tarifaHoraRenta: 1450,
    importeTotalRenta: 15225
  },
  {
    id: "B002",
    folio: "BIT-2025-041",
    trabajadorId: "T002",
    trabajadorNombre: "Pedro Gómez",
    maquinaId: "M002",
    maquinaNombre: "Retroexcavadora JD 310L",
    fecha: "2025-04-27",
    cliente: "Gobierno CDMX - Obras Públicas",
    obraUbicacion: "Remodelación Centro Histórico (Calle 5 de Mayo)",
    horaInicio: "07:00 AM",
    horaFin: "03:00 PM",
    horasEfectivas: 8.0,
    horasExtras: 0,
    horometroInicial: 885.0,
    horometroFinal: 893.0,
    actividadRealizada: "Demolición de banquetas dañadas, retiro de escombro y apertura de cajas para tubería de gas natural.",
    firmaCliente: {
      firmado: true,
      nombreResidente: "Arq. Manuel Morales",
      cargoResidente: "Supervisor Obras CDMX",
      fechaFirma: "2025-04-27 03:15 PM"
    },
    estadoCobro: "Facturado",
    tarifaHoraRenta: 950,
    importeTotalRenta: 7600
  },
  {
    id: "B003",
    folio: "BIT-2025-040",
    trabajadorId: "T004",
    trabajadorNombre: "Luis Torres",
    maquinaId: "M004",
    maquinaNombre: "Camión Volteo Kenworth 14m³",
    fecha: "2025-04-26",
    cliente: "Constructora ABC / SCT",
    obraUbicacion: "Tramo Carretero Atizapán Km 14+200",
    horaInicio: "06:30 AM",
    horaFin: "06:00 PM",
    horasEfectivas: 8.0,
    horasExtras: 3.5,
    horometroInicial: 3410.0,
    horometroFinal: 3421.5,
    actividadRealizada: "12 viajes de acarreo de base hidráulica y tepetate desde banco de tiro a terraplén principal.",
    firmaCliente: {
      firmado: false,
    nombreResidente: "Ing. Fernando Silva",
      cargoResidente: "Jefe de Frente SCT",
    },
    estadoCobro: "Pendiente Firma",
    tarifaHoraRenta: 850,
    importeTotalRenta: 9775
  }
];

export const registrosAsistencia: RegistroAsistencia[] = [
  { 
    id: "A001", 
    trabajadorId: "T001", 
    fecha: "2025-04-27", 
    horaEntrada: "07:05 AM", 
    horaMarcajeExacta: "07:04:48 AM",
    horaSalida: "05:00 PM",
    horaSalidaExacta: "05:00:15 PM",
    horasTrabajadasOrdinarias: 8.0,
    estado: "Puntual", 
    ubicacion: "Fracc. Valle Sur (Frente a Manzana 4)", 
    coordenadas: { lat: 19.3423, lng: -99.1841 },
    salidaCoordenadas: { lat: 19.3425, lng: -99.1840 },
    salidaUbicacion: "Fracc. Valle Sur (Caseta de Salida)",
    obraAsignada: "Fraccionamiento Valle Sur",
    obraCoordenadas: { lat: 19.3421, lng: -99.1843 },
    distanciaMetros: 28,
    radioPermitidoMetros: 2000,
    enSitio: true,
    precisionGpsMetros: 6,
    dispositivo: "Samsung Galaxy A54 · GPS Activo",
    bateria: 92,
    horasExtra: {
      inicio: "05:00 PM",
      fin: "08:30 PM",
      horasCalculadas: 3.5,
      tarifaPorHora: 80,
      montoTotal: 280,
      estado: "Aprobado",
      motivo: "Colado continuo de cimentación y losa",
      coordenadasInicio: { lat: 19.3423, lng: -99.1841 },
      coordenadasFin: { lat: 19.3426, lng: -99.1842 }
    },
    notas: "Marcaje verificado dentro del polígono de obra (radio 2km)."
  },
  { 
    id: "A002", 
    trabajadorId: "T002", 
    fecha: "2025-04-27", 
    horaEntrada: "06:58 AM", 
    horaMarcajeExacta: "06:58:12 AM",
    horaSalida: "04:30 PM",
    horaSalidaExacta: "04:30:20 PM",
    horasTrabajadasOrdinarias: 8.5,
    estado: "Puntual", 
    ubicacion: "Centro Histórico (Acceso Calle Madero)", 
    coordenadas: { lat: 19.4328, lng: -99.1330 },
    salidaCoordenadas: { lat: 19.4327, lng: -99.1331 },
    salidaUbicacion: "Centro Histórico (Salida Madero)",
    obraAsignada: "Remodelación Centro Histórico",
    obraCoordenadas: { lat: 19.4326, lng: -99.1332 },
    distanciaMetros: 35,
    radioPermitidoMetros: 2000,
    enSitio: true,
    precisionGpsMetros: 8,
    dispositivo: "Xiaomi Redmi Note 12 · GPS Activo",
    bateria: 87,
    horasExtra: {
      inicio: "04:30 PM",
      fin: "07:00 PM",
      horasCalculadas: 2.5,
      tarifaPorHora: 75,
      montoTotal: 187.5,
      estado: "Aprobado",
      motivo: "Nivelación nocturna de terreno para pavimentación",
      coordenadasInicio: { lat: 19.4328, lng: -99.1330 }
    },
    notas: "Marcaje verificado en punto de control de acceso."
  },
  { 
    id: "A003", 
    trabajadorId: "T004", 
    fecha: "2025-04-27", 
    horaEntrada: "08:15 AM", 
    horaMarcajeExacta: "08:15:33 AM",
    horasTrabajadasOrdinarias: 7.0,
    estado: "Retardo", 
    ubicacion: "Av. Insurgentes Sur #1420 (Fuera de radio 2km)", 
    coordenadas: { lat: 19.3780, lng: -99.1720 },
    obraAsignada: "Fraccionamiento Valle Sur",
    obraCoordenadas: { lat: 19.3421, lng: -99.1843 },
    distanciaMetros: 4210,
    radioPermitidoMetros: 2000,
    enSitio: false,
    precisionGpsMetros: 14,
    dispositivo: "Motorola Moto G84 · GPS Activo",
    bateria: 48,
    notas: "ALERTA DE GEOCERCA: El marcaje se realizó a 4.2 km de distancia, superando el radio de 2 km de la obra."
  },
  { 
    id: "A004", 
    trabajadorId: "T003", 
    fecha: "2025-04-27", 
    horaEntrada: "08:30 AM", 
    horaMarcajeExacta: "08:29:50 AM",
    horaSalida: "02:15 PM",
    horaSalidaExacta: "02:15:40 PM",
    horasTrabajadasOrdinarias: 5.75,
    salidaAnticipada: true,
    motivoSalidaAnticipada: "Cita médica programada en clínica IMSS.",
    estado: "Salida Anticipada", 
    ubicacion: "Oficina Central SVR (Recepción)", 
    coordenadas: { lat: 19.4106, lng: -99.1677 },
    obraAsignada: "Oficina Central SVR",
    obraCoordenadas: { lat: 19.4105, lng: -99.1678 },
    distanciaMetros: 15,
    radioPermitidoMetros: 500,
    enSitio: true,
    precisionGpsMetros: 4,
    dispositivo: "iPhone 13 · iOS 17.4",
    bateria: 95,
    notas: "ALERTA: Retiro anticipado registrado con motivo médico."
  },
];

export const asistenciaSemanalData: AsistenciaSemanalTrabajador[] = [
  {
    trabajadorId: "T001",
    semana: "Semana 17 (21 Abr - 26 Abr 2025)",
    totalDiasAsistidos: 6,
    totalFaltas: 0,
    totalRetardos: 1,
    totalHorasOrdinarias: 48,
    totalHorasExtra: 6.5,
    dias: [
      { dia: 'Lun', fecha: '21 Abr', estado: 'Puntual', horaEntrada: '06:55 AM', horaSalida: '05:00 PM', horasTrabajadas: 8, horasExtra: 2.0, enSitioGps: true },
      { dia: 'Mar', fecha: '22 Abr', estado: 'Puntual', horaEntrada: '07:00 AM', horaSalida: '05:00 PM', horasTrabajadas: 8, horasExtra: 0, enSitioGps: true },
      { dia: 'Mie', fecha: '23 Abr', estado: 'Retardo', horaEntrada: '07:22 AM', horaSalida: '05:00 PM', horasTrabajadas: 8, horasExtra: 1.0, enSitioGps: true },
      { dia: 'Jue', fecha: '24 Abr', estado: 'Puntual', horaEntrada: '06:58 AM', horaSalida: '05:00 PM', horasTrabajadas: 8, horasExtra: 0, enSitioGps: true },
      { dia: 'Vie', fecha: '25 Abr', estado: 'Puntual', horaEntrada: '07:02 AM', horaSalida: '05:00 PM', horasTrabajadas: 8, horasExtra: 3.5, enSitioGps: true },
      { dia: 'Sab', fecha: '26 Abr', estado: 'Puntual', horaEntrada: '07:00 AM', horaSalida: '03:00 PM', horasTrabajadas: 8, horasExtra: 0, enSitioGps: true }
    ]
  },
  {
    trabajadorId: "T002",
    semana: "Semana 17 (21 Abr - 26 Abr 2025)",
    totalDiasAsistidos: 6,
    totalFaltas: 0,
    totalRetardos: 0,
    totalHorasOrdinarias: 48,
    totalHorasExtra: 4.5,
    dias: [
      { dia: 'Lun', fecha: '21 Abr', estado: 'Puntual', horaEntrada: '06:50 AM', horaSalida: '05:00 PM', horasTrabajadas: 8, horasExtra: 2.0, enSitioGps: true },
      { dia: 'Mar', fecha: '22 Abr', estado: 'Puntual', horaEntrada: '06:55 AM', horaSalida: '05:00 PM', horasTrabajadas: 8, horasExtra: 0, enSitioGps: true },
      { dia: 'Mie', fecha: '23 Abr', estado: 'Puntual', horaEntrada: '06:58 AM', horaSalida: '05:00 PM', horasTrabajadas: 8, horasExtra: 0, enSitioGps: true },
      { dia: 'Jue', fecha: '24 Abr', estado: 'Puntual', horaEntrada: '06:52 AM', horaSalida: '05:00 PM', horasTrabajadas: 8, horasExtra: 2.5, enSitioGps: true },
      { dia: 'Vie', fecha: '25 Abr', estado: 'Puntual', horaEntrada: '06:58 AM', horaSalida: '05:00 PM', horasTrabajadas: 8, horasExtra: 0, enSitioGps: true },
      { dia: 'Sab', fecha: '26 Abr', estado: 'Puntual', horaEntrada: '07:00 AM', horaSalida: '03:00 PM', horasTrabajadas: 8, horasExtra: 0, enSitioGps: true }
    ]
  },
  {
    trabajadorId: "T004",
    semana: "Semana 17 (21 Abr - 26 Abr 2025)",
    totalDiasAsistidos: 5,
    totalFaltas: 1,
    totalRetardos: 2,
    totalHorasOrdinarias: 40,
    totalHorasExtra: 0,
    dias: [
      { dia: 'Lun', fecha: '21 Abr', estado: 'Retardo', horaEntrada: '07:45 AM', horaSalida: '05:00 PM', horasTrabajadas: 8, horasExtra: 0, enSitioGps: true },
      { dia: 'Mar', fecha: '22 Abr', estado: 'Puntual', horaEntrada: '07:05 AM', horaSalida: '05:00 PM', horasTrabajadas: 8, horasExtra: 0, enSitioGps: true },
      { dia: 'Mie', fecha: '23 Abr', estado: 'Falta', horasTrabajadas: 0, horasExtra: 0, enSitioGps: false, motivo: 'Inasistencia no justificada' },
      { dia: 'Jue', fecha: '24 Abr', estado: 'Puntual', horaEntrada: '07:00 AM', horaSalida: '05:00 PM', horasTrabajadas: 8, horasExtra: 0, enSitioGps: true },
      { dia: 'Vie', fecha: '25 Abr', estado: 'Retardo', horaEntrada: '08:15 AM', horaSalida: '05:00 PM', horasTrabajadas: 8, horasExtra: 0, enSitioGps: false, motivo: 'Marcaje fuera de geocerca' },
      { dia: 'Sab', fecha: '26 Abr', estado: 'Puntual', horaEntrada: '07:00 AM', horaSalida: '03:00 PM', horasTrabajadas: 8, horasExtra: 0, enSitioGps: true }
    ]
  },
  {
    trabajadorId: "T003",
    semana: "Semana 17 (21 Abr - 26 Abr 2025)",
    totalDiasAsistidos: 6,
    totalFaltas: 0,
    totalRetardos: 0,
    totalHorasOrdinarias: 45.75,
    totalHorasExtra: 0,
    dias: [
      { dia: 'Lun', fecha: '21 Abr', estado: 'Puntual', horaEntrada: '08:30 AM', horaSalida: '05:00 PM', horasTrabajadas: 8, horasExtra: 0, enSitioGps: true },
      { dia: 'Mar', fecha: '22 Abr', estado: 'Puntual', horaEntrada: '08:28 AM', horaSalida: '05:00 PM', horasTrabajadas: 8, horasExtra: 0, enSitioGps: true },
      { dia: 'Mie', fecha: '23 Abr', estado: 'Puntual', horaEntrada: '08:30 AM', horaSalida: '05:00 PM', horasTrabajadas: 8, horasExtra: 0, enSitioGps: true },
      { dia: 'Jue', fecha: '24 Abr', estado: 'Puntual', horaEntrada: '08:25 AM', horaSalida: '05:00 PM', horasTrabajadas: 8, horasExtra: 0, enSitioGps: true },
      { dia: 'Vie', fecha: '25 Abr', estado: 'Salida Anticipada', horaEntrada: '08:30 AM', horaSalida: '02:15 PM', horasTrabajadas: 5.75, horasExtra: 0, enSitioGps: true, motivo: 'Cita médica IMSS' },
      { dia: 'Sab', fecha: '26 Abr', estado: 'Puntual', horaEntrada: '08:30 AM', horaSalida: '02:30 PM', horasTrabajadas: 6, horasExtra: 0, enSitioGps: true }
    ]
  }
];
