-- AlterEnum: Add bitacora operacion audit actions
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'BITACORA_CREADA';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'BITACORA_ACTUALIZADA';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'BITACORA_ELIMINADA';
