-- AlterEnum: Add mantenimiento y combustible audit actions
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'MANTENIMIENTO_REGISTRADO';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'MANTENIMIENTO_ACTUALIZADO';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'MANTENIMIENTO_ELIMINADO';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'COMBUSTIBLE_ACTUALIZADO';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'COMBUSTIBLE_ELIMINADO';
