-- Agrega valores de auditoria para el módulo de Asistencia (RRHH):
-- marcaje GPS de entrada/salida, pase de lista por cuadrilla, faltas,
-- cambios manuales de estado y el flujo de aprobación de horas extra.
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'ASISTENCIA_ENTRADA_REGISTRADA';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'ASISTENCIA_SALIDA_REGISTRADA';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'ASISTENCIA_CUADRILLA_REGISTRADA';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'ASISTENCIA_FALTA_REGISTRADA';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'ASISTENCIA_ESTADO_ACTUALIZADO';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'ASISTENCIA_HORAS_EXTRA_REGISTRADAS';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'ASISTENCIA_HORAS_EXTRA_APROBADAS';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'ASISTENCIA_HORAS_EXTRA_RECHAZADAS';
