-- Agrega valores de auditoria para el modulo de trabajadores (RRHH) y
-- bitacoras de renta diaria (distintas de BITACORA_* que ya es de Operaciones).
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'TRABAJADOR_CREADO';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'TRABAJADOR_ACTUALIZADO';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'TRABAJADOR_ELIMINADO';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'TRABAJADOR_LIQUIDADO';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'BITACORA_RENTA_CREADA';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'BITACORA_RENTA_ACTUALIZADA';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'BITACORA_RENTA_ELIMINADA';
