-- AlterEnum: Add inventory audit actions
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'ARTICULO_CREADO';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'ARTICULO_ACTUALIZADO';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'ARTICULO_ELIMINADO';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'MOVIMIENTO_REGISTRADO';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'STOCK_BAJO_DETECTADO';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'STOCK_BAJO_RESUELTO';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'STOCK_INSUFICIENTE';
